services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ALHambra99!
      MYSQL_DATABASE: alhambra
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - wakaf-net
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - wakaf-net

volumes:
  mysql_data:

networks:
  wakaf-net:
    external: true