# This is a basic workflow to help you get started with Actions
name: wakaf
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: faturfawkes/alhambra-wakaf
      - 
        name: executing remote ssh using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop wakaf
            docker rm wakaf
            docker rmi faturfawkes/alhambra-wakaf
            docker run --name wakaf --link redis:6389 -p 8080:8000 -e SERVER_PORT=${{ secrets.SERVER_PORT }} -e DB_USERNAME=${{ secrets.DB_USERNAME }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e DB_HOST=${{ secrets.DB_HOST }} -e DB_PORT=${{ secrets.DB_PORT }} -e DB_NAME=${{ secrets.DB_NAME }} -e IMAGEIO_PUBLIC=${{ secrets.IMAGEIO_PUBLIC }} -e IMAGEIO_PRIVATE=${{ secrets.IMAGEIO_PRIVATE }} -e SECRET_JWT=${{ secrets.SECRET_JWT }} -e SALT1=${{ secrets.SALT1 }} -e SALT2=${{ secrets.SALT2 }} -e JWT_EXPIRY=${{ secrets.JWT_EXPIRY }} -e SERVER_KEY=${{ secrets.MIDTRANS_SERVER_KEY }} -e CLIENT_KEY=${{ secrets.MIDTRANS_CLIENT_KEY }}  -d faturfawkes/alhambra-wakaf:latest